server:
  port: 8011

spring:
  application:
    name: integrated-storage
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/integrated-storage?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
        group: integrated-example
      config:
        server-addr: nacos-server:8848
        group: integrated-example
  config:
    import:
      - optional:nacos:integrated-storage.yaml
      - optional:nacos:datasource-config.yaml

seata:
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
  service:
    vgroup-mapping:
      integrated-storage-group: default
    grouplist:
      default: seata-server:8091
